@startgantt 期未專案甘特圖
Project starts 2024-12-01
[完成需求分析] lasts 2 day
[完成設計] lasts 1 day
[程式開發（完成棋盤和演算法設計）] lasts 5 day
[完成棋盤和演算法測試] lasts 1 day
[重構棋盤和演算法] lasts 1 day
[完成類別圖] lasts 1 day
[程式開發（完成 IO 設備）] lasts 2 day
[程式開發（完成遊戲邏輯）] lasts 3 day
[完成 IO 和遊戲邏輯測試] lasts 1 day
[重構 IO 和遊戲邏輯] lasts 1 day
[更新類別圖] lasts 2 day
[完成遊戲狀態機圖] lasts 2 day
[總測試] lasts 1 day

[完成需求分析] -> [完成設計]
[完成設計] -> [程式開發（完成棋盤和演算法設計）]
[程式開發（完成棋盤和演算法設計）] -> [完成棋盤和演算法測試]
[完成棋盤和演算法測試] -> [重構棋盤和演算法]
[重構棋盤和演算法] -> [完成類別圖]
[完成類別圖] -> [程式開發（完成 IO 設備）]
[程式開發（完成 IO 設備）] -> [程式開發（完成遊戲邏輯）]
[程式開發（完成遊戲邏輯）] -> [完成 IO 和遊戲邏輯測試]
[完成 IO 和遊戲邏輯測試] -> [重構 IO 和遊戲邏輯]
[重構 IO 和遊戲邏輯] -> [更新類別圖]
[重構 IO 和遊戲邏輯] -> [完成遊戲狀態機圖]
[完成遊戲狀態機圖] -> [總測試]

@endgantt